### PR TITLE
Issue #10

### PR DESCRIPTION
**Pull request by soliashuptar**
Added a PersonManagerValidator for validating two constraints: "No one should be able to manage themselves." and "Manager cannot manage a non-employee.". Also added a new method isEmployee() for Person for convenience and covered those cases with tests.

### CODE REVIEW

**Comment by vlad-bilyk** [comment]
A better way to check if a Person is employee in `isEmployee()` method would be to check whether or not `employeeNo` is empty instead of checking whether it is null.

**Review by vlad-bilyk — CHANGES_REQUESTED** [review]
A better way to check if a Person is employee in `isEmployee()` method would be to check whether or not `employeeNo` is empty instead of checking whether it is null.

**Comment by soliashuptar** [comment]
> A better way to check if a Person is employee in `isEmployee()` method would be to check whether or not `employeeNo` is empty instead of checking whether it is null.

Okay, thanks! Going to fix it in a moment, wait a second

**Review by vlad-bilyk — APPROVED** [review]
Nice! For future reference: StringUtils.isBlank(string) returns true even if you pass null as an argument.

**Comment by vlad-bilyk** [comment]
You can merge now if you want

**Pull request merged**
