### PR TITLE
#17 Added Product Entity Centre/Master

### PR DESCRIPTION
**Pull request by soliashuptar**
Added Product Entity Centre/Master.

### CODE REVIEW

**Review by Sofiia2001 — CHANGES_REQUESTED** [review]
I have tried to test Product Entity Centre/Master on web server and it turns out there is some problem with loading the entity there.
The error occured is the following: `Could not load element tg-miproduct-centre due to [SyntaxError: Unexpected identifier].
Error: Could not load element tg-miproduct-centre due to [SyntaxError: Unexpected identifier].
    at https://tgdev.com/resources/element_loader/tg-element-loader.js:207:27`

I suggest you to regenerate files (including ProductWebUiCofig, MiProduct) using TG plugin and report if everything is Ok.

**Comment by soliashuptar** [comment]
Thanks!

**Review by vlad-bilyk — CHANGES_REQUESTED** [review]
Validator that doesnt allow numbers in product name? T_T

**Review by vlad-bilyk — APPROVED** [review]
Nice!

**Pull request merged**
